### ISSUE TITLE
Support tasty command-line option --ansi-tricks=false

### ISSUE THREAD

**Issue by andreasabel** [phile314/tasty-silver#17]
Upon our wish, `tasty` supports now an option `--ansi-tricks=false` that should help getting clearer output on travis-ci.org, which is garbled: https://github.com/feuerbach/tasty/issues/250

Could `tasty-silver` also support it?  
Needed for https://github.com/agda/agda/issues/3905

**Comment by phile314** [comment]
Done thanks to L-TChen and released just now:

http://hackage.haskell.org/package/tasty-silver-3.1.13
