### ISSUE TITLE
Successful calls to `git diff` take the error path

### ISSUE THREAD

**Issue by croyzor** [phile314/tasty-silver#20]
At least on my (mac os) machine, the default setup for `git diff` is to copy the return code system of `diff`, meaning:

`0` - if the files are the same

`1` - if the files differ

`2` - if something actually went wrong

Since version 3.1.10, the return code is being checked and if the files differ it's treated as an error, resulting in the message "Call to `git diff` failed" followed by the unformatted output of the diff (example below)

```
tests: Call to `git diff` failed: (ExitFailure 1,"diff --git a/private/var/folders/6h/vp6kwdn16vlb5g6y9g9xvw6c0000gn/T/hello_alt11597-0.golden b/private/var/folders/6h/vp6kwdn16vlb5g6y9g9xvw6c0000gn/T/hello_alt11597-1.actual\nindex e965047..acad3f2 100644\n--- a/private/var/folders/6h/vp6kwdn16vlb5g6y9g9xvw6c0000gn/T/hello_alt11597-0.golden\n+++ b/private/var/folders/6h/vp6kwdn16vlb5g6y9g9xvw6c0000gn/T/hello_alt11597-1.actual\n@@ -1 +1,3 @@\n-Hello\n+ret > ExitSuccess\n+out > Hello\n+out >\n","")
CallStack (from HasCallStack):
  error, called at ./Test/Tasty/Silver/Interactive.hs:189:16 in tsty-slvr-3.1.13-25848db6:Test.Tasty.Silver.Interactive
```

**Comment by phile314** [comment]
Released as https://hackage.haskell.org/package/tasty-silver-3.1.14
