### ISSUE TITLE
`--accept` with `Test.Tasty.Silver.Interactive.defaultMain` doesn't update/create golden files

### ISSUE THREAD

**Issue by german1608** [phile314/tasty-silver#24]
Just that, on tasty-silver-1.3.15.

If I use the `defaultMain` from `tasty` package, it correctly updates the values.

**Comment by phile314** [comment]
To be honest, it has been a long time since I touched that code so I don't really remember what is happening there ....

I probably will not have the time to look at this any time soon. Accepting a PR fixing this would be no problem though ;-)

**Comment by german1608** [comment]
@phile314 thanks for your response!

I'm quite bussy right now too, but I can add this issue to my personal list to try to fix it soon, but no promises at all :smile:

I'll keep the issue open until its fixed

**Comment by aronerben** [comment]
Is there any update on this? It would be great if this feature worked with `defaultMain` from `tasty-silver`!

**Comment by phile314** [comment]
I am no longer using tasty-silver myself. I will not fix this myself; I am happy to accept a PR though.

**Comment by andreasabel** [comment]
I have to update > 1000 golden values so it is reasonable to fix this first.  PR coming.
