### ISSUE TITLE
Older releases need revisions

### ISSUE THREAD

**Issue by Bodigrim** [phile314/tasty-silver#34]
https://matrix.hackage.haskell.org/#/package/tasty-silver
CC @andreasabel

**Comment by andreasabel** [comment]
@Bodigrim : Which old versions are you interested in?  How deep shall archeology dig?

**Comment by Bodigrim** [comment]
I'm not interested in archeology, it's just that old versions keep popping up in build plans. For my purposes it would be enough to revise versions, which are advertised as buildable with GHC 8.10.

**Comment by andreasabel** [comment]
I now revised version back to 3.1.8, the rest is GHC-7 only. Relevant upper bounds are on:
- `base`: < 4.13, 4.11, 4.9
- `tasty`: < 1.14
- `optparse-applicative`: < 0.13

**Comment by andreasabel** [comment]
> I'm not interested in archeology, it's just that old versions keep popping up in build plans. For my purposes it would be enough to revise versions, which are advertised as buildable with GHC 8.10.

OK, then I have over-fulfilled your request already!

**Comment by andreasabel** [comment]
I applied these bounds now to >= 3.1 && < 3.1.8, not checking actual buildability.
>     * `base`: < 4.9
>     * `tasty`: < 1.14
>     * `optparse-applicative`: < 0.13

This should eliminate these versions from build-plans for GHC >= 8.

**Comment by andreasabel** [comment]
I further applied these bounds to 3.0.*.

**Comment by Bodigrim** [comment]
Thanks!

**Comment by andreasabel** [comment]
Debugging build failure 
https://matrix.hackage.haskell.org/#/package/tasty-silver/3.0.1.0/ghc-7.4.2@1637957897
```
Test/Tasty/Silver/Interactive.hs:163:15:
    Not in scope: `B.fromStrict'
```
would benefit from information where `fromStrict` was introduced to `Data.ByteString.Lazy`:
- https://github.com/haskell/bytestring/issues/442

**Comment by andreasabel** [comment]
> * `tasty`: < 1.14

Don't know how I got to this, but `tasty < 1.14` does not make sense, as even today the highest version is `1.5`.
Maybe I meant `< 1.4`?

**Comment by andreasabel** [comment]
I now revised `< 1.14` to `< 1.4` on hackage, e.g. https://hackage.haskell.org/package/tasty-silver-3.0.2.2/revisions/ .
